version: "3"

services:
  postgres:
    image: postgres:11.8-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=audit-poc
      - POSTGRES_PASSWORD=audit-poc
      - MAX_CONNECTIONS=300
    networks:
      - development

networks:
  development:
    driver: bridge